name: furcare_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  geolocator: ^14.0.2
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  map_launcher: ^4.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^31.1.17
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/furcare_logo.png
    - assets/carousel_1.jpeg
    - assets/carousel_2.jpeg
    - assets/carousel_3.jpeg
    - assets/carousel_4.jpeg
    - assets/carousel_5.jpeg
    - assets/carousel_6.jpeg
    - assets/carousel_7.jpeg
    - assets/carousel_8.jpeg
    - assets/image_1.jpg
    - assets/image_2.jpg
    - assets/image_3.jpg
    - assets/gcash.jpg
